resource_group_name   = "vladimir-ryadovoy-diploma"
storage_account_name  = "ryadovoystoracc"
container_name        = "tfstate"
access_key            = "$ACCOUNT_KEY"
key                   = "terraform.tfstate"